version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123ord
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 123
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: python app.py
volumes:
  postgres_data: